### PR TITLE
more threads, clean up

### PR DESCRIPTION
**Pull request by LudwigKnuepfer**
Have several thread creation/exit/switch execution paths.

```
main: starting
main: exiting
2nd: starting
3rd: starting
3rd: exiting
2nd: exiting
4th: starting
4th: exiting
```

### CODE REVIEW

**Comment by mehlis** [comment]
```
$ valgrind ./bin/test_thread_exit.elf
==20253== Memcheck, a memory error detector
==20253== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==20253== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==20253== Command: ./bin/test_thread_exit.elf
==20253== 
RIOT native interrupts/signals initialized.
LED_GREEN_OFF
LED_RED_ON
RIOT native board initialized.
RIOT native hardware initialization complete.

kernel_init(): This is RIOT! (Version: 2013.08-747-gd82a-fix-yield)
Scheduler...[OK]
kernel_init(): jumping into first task...
main: starting
main: exiting
2nd: starting
3rd: starting
3rd: exiting
==20253== Invalid write of size 4
==20253==    at 0x804C77E: thread_create (thread.c:156)
==20253==    by 0x804CD39: second_thread (main.c:36)
==20253==    by 0x44B71CEA: makecontext (in /usr/lib/libc-2.17.so)
==20253==    by 0x805B7CB: ???
==20253==  Address 0x80637c0 is 15756 bytes inside data symbol "third_thread_stack"
==20253== 
2nd: exiting
==20253== Invalid write of size 4
==20253==    at 0x44B71C67: setcontext (in /usr/lib/libc-2.17.so)
==20253==  Address 0x8063888 is 15956 bytes inside data symbol "third_thread_stack"
==20253== 
==20253== Invalid read of size 4
==20253==    at 0x44B71C7D: setcontext (in /usr/lib/libc-2.17.so)
==20253==    by 0x804CBFF: ??? (in /home/c/git/RIOT-OS/projects/test_thread_exit/bin/test_thread_exit.elf)
==20253==  Address 0x8063888 is 15956 bytes inside data symbol "third_thread_stack"
==20253== 
4th: starting
4th: exiting
```

**Comment by LudwigKnuepfer** [comment]
I know, this could indicate a problem in native.

**Comment by mehlis** [comment]
ACK - better to have a failing testcase than no test case

@LudwigOrtmann merge?

**Comment by OlegHahm** [comment]
ACK and go.

**Pull request merged**
