### PR TITLE
eip stack test

### PR DESCRIPTION
**Pull request by LudwigKnuepfer**

### CODE REVIEW

**Comment by LudwigKnuepfer** [comment]
The test shows two threads that get interrupted keep their program counters (i.e. both threads work). This is not the case with current master.

**Comment by LudwigKnuepfer** [comment]
Also, tests work with/without valgrind.

**Comment by LudwigKnuepfer** [comment]
A working test prints varying characters.

**Comment by ghost** [comment]
Merged build triggered.

**Comment by ghost** [comment]
Merged build started.

**Comment by ghost** [comment]
Merged build finished.

**Comment by LudwigKnuepfer** [comment]
abandoned

**Comment by OlegHahm** [comment]
Didn't even remember this repository. (Not even the Github organization.) ;-)

**Comment by miri64** [comment]
I think we just moved the repository here when we replaced projects with applications ;-)

**Pull request closed without merging**
