### PR TITLE
default projects merge and improve

### PR DESCRIPTION
**Pull request by LudwigKnuepfer**
default:
add license header
initialize transceiver thread for all available transceivers
add radio thread when transceiver is available
register radio thread with transceiver for available transceivers
clean up imports
clean up Makefile
set default target to native
include all available modules for native target
add -DSCHEDSTATISTICS option (disabled by default)

default-native:
remove default-native project

### CODE REVIEW

**Comment by mehlis** [comment]
ACK @LudwigOrtmann ready for merge!

**Comment by LudwigKnuepfer** [comment]
I'd like @kaspar030 to acknowledge this as it adds a copyright header (has been unlicensed before).

**Comment by OlegHahm** [comment]
Looks ugly. Why not just add a header like

```
uint16_t transceivers = 0;
#ifdef MODULE_CC2420
transceivers |= TRANSCEIVER_CC2420
#endif
...
```

?

**Comment by LudwigKnuepfer** [comment]
good point

**Comment by kaspar030** [comment]
ACK from my side for the license header!

**Pull request merged**
