### PR TITLE
Fixes for CC2420 test application

### PR DESCRIPTION
**Pull request by rousselk**
These corrections allow the CC2420 test application to compile and execute successfully, at least on Zolertia Z1 port.

### CODE REVIEW

**Comment by OlegHahm** [comment]
The PR looks good, but where's the PR for the Z1 in RIOT? ;)

**Comment by rousselk** [comment]
Yes, it's probably time to push it ; it still depends on #881 and #882 on main repository still.

**Comment by rousselk** [comment]
Z1 port is now PR #893 in main RIOT repo.

**Comment by rousselk** [comment]
Is it OK to merge this PR?

**Comment by OlegHahm** [comment]
ACK and go.

**Pull request merged**
