### PR TITLE
add memory mgnt test code

### PR DESCRIPTION
**Pull request by mehlis**
test case for https://github.com/RIOT-OS/RIOT/pull/292

### CODE REVIEW

**Comment by miri64** [comment]
Does not build

**Comment by mehlis** [comment]
on native it's building, on msba2 too, with my machine...

can you provide me more information?

**Comment by miri64** [comment]
Before the compiler complained about missing modules, but this does not seem the problem anymore (propably Problem existing between keyboard and chair). It builds now when I remove commits 4f4c4bf and 6a317cd so maybe this PR is not the problem ;-)

(sorry for the german output)

``` bash
export BOARD=msba2; make
```

```
Compiling.... main.c

Building project test_memmgnt for msba2 w/ MCU lpc2387.
"make" -C /home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../boards
make[1]: Betrete Verzeichnis '/home/martin/Repositories/RIOT-OS/boards'
make -C msba2
make[2]: Betrete Verzeichnis '/home/martin/Repositories/RIOT-OS/boards/msba2'
mkdir -p bin/
make -C ../msba2-common
make[3]: Betrete Verzeichnis '/home/martin/Repositories/RIOT-OS/boards/msba2-common'
make -C drivers
make[4]: Betrete Verzeichnis '/home/martin/Repositories/RIOT-OS/boards/msba2-common/drivers'
In file included from /home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/sys/include/radio/radio.h:39,
                 from /home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/drivers/cc110x_ng/include/cc110x_ng.h:20,
                 from msba2-cc110x.c:46:
/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/sys/include/radio/types.h:76: error: expected specifier-qualifier-list before 'radio_packet_length_t'
make[4]: *** [/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../boards/msba2/bin/msba2-cc110x.o] Fehler 1
make[4]: Verlasse Verzeichnis '/home/martin/Repositories/RIOT-OS/boards/msba2-common/drivers'
make[3]: *** [all] Fehler 2
make[3]: Verlasse Verzeichnis '/home/martin/Repositories/RIOT-OS/boards/msba2-common'
make[2]: *** [all] Fehler 2
make[2]: Verlasse Verzeichnis '/home/martin/Repositories/RIOT-OS/boards/msba2'
make[1]: *** [all] Fehler 2
make[1]: Verlasse Verzeichnis '/home/martin/Repositories/RIOT-OS/boards'
make: *** [all] Fehler 2
```

``` bash
export BOARD=native; make
```

```

Compiling.... main.c

cc -DBOARD=NATIVE -std=gnu99 -Wall -m32 -DMODULE_MEMMGNT -DMODULE_CPU -DMODULE_CORE -DMODULE_SYS -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../boards/native/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/core/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/cpu/native/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/sys/lib -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/sys/include/ -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/drivers/include/ -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../boards/native/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/cpu/native/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/core/include -c main.c -o /home/martin/Repositories/RIOT-OS/projects/test_memmgnt/bin/main.o
Building project test_memmgnt for native w/ MCU native.
"make" -C /home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../boards
make[1]: Betrete Verzeichnis '/home/martin/Repositories/RIOT-OS/boards'
make -C native
make[2]: Betrete Verzeichnis '/home/martin/Repositories/RIOT-OS/boards/native'
mkdir -p bin/
cc -DBOARD=NATIVE -std=gnu99 -Wall -m32 -DMODULE_MEMMGNT -DMODULE_CPU -DMODULE_CORE -DMODULE_SYS -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../boards/native/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/core/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/cpu/native/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/sys/lib -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/sys/include/ -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/drivers/include/ -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../boards/native/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/cpu/native/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/core/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/cpu/native/include/ -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../boards/native/include/    -c board_config.c -o bin/board_config.o
cc -DBOARD=NATIVE -std=gnu99 -Wall -m32 -DMODULE_MEMMGNT -DMODULE_CPU -DMODULE_CORE -DMODULE_SYS -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../boards/native/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/core/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/cpu/native/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/sys/lib -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/sys/include/ -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/drivers/include/ -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../boards/native/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/cpu/native/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/core/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/cpu/native/include/ -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../boards/native/include/    -MM board_config.c > bin/board_config.d
mkdir -p bin/
cc -DBOARD=NATIVE -std=gnu99 -Wall -m32 -DMODULE_MEMMGNT -DMODULE_CPU -DMODULE_CORE -DMODULE_SYS -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../boards/native/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/core/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/cpu/native/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/sys/lib -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/sys/include/ -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/drivers/include/ -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../boards/native/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/cpu/native/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/core/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/cpu/native/include/ -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../boards/native/include/    -c board_init.c -o bin/board_init.o
cc -DBOARD=NATIVE -std=gnu99 -Wall -m32 -DMODULE_MEMMGNT -DMODULE_CPU -DMODULE_CORE -DMODULE_SYS -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../boards/native/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/core/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/cpu/native/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/sys/lib -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/sys/include/ -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/drivers/include/ -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../boards/native/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/cpu/native/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/core/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/cpu/native/include/ -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../boards/native/include/    -MM board_init.c > bin/board_init.d
make -C drivers
make[3]: Betrete Verzeichnis '/home/martin/Repositories/RIOT-OS/boards/native/drivers'
cc -DBOARD=NATIVE -std=gnu99 -Wall -m32 -DMODULE_MEMMGNT -DMODULE_CPU -DMODULE_CORE -DMODULE_SYS -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../boards/native/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/core/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/cpu/native/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/sys/lib -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/sys/include/ -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/drivers/include/ -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../boards/native/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/cpu/native/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/core/include -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/cpu/native/include/ -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../boards/native/include/ -I/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../boards/native/include/    -c native-led.c -o /home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../boards/native/bin/native-led.o
make[3]: Verlasse Verzeichnis '/home/martin/Repositories/RIOT-OS/boards/native/drivers'
make[2]: Verlasse Verzeichnis '/home/martin/Repositories/RIOT-OS/boards/native'
make[1]: Verlasse Verzeichnis '/home/martin/Repositories/RIOT-OS/boards'
"make" -C /home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT
make[1]: Betrete Verzeichnis '/home/martin/Repositories/RIOT-OS/RIOT'
mkdir -p /home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/bin/
make[2]: Betrete Verzeichnis '/home/martin/Repositories/RIOT-OS/RIOT/cpu'
make[3]: Betrete Verzeichnis '/home/martin/Repositories/RIOT-OS/RIOT/cpu/native'
In file included from /home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/cpu/native/include/tap.h:22:0,
                 from startup.c:24:
/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/sys/include/radio/types.h:76:5: error: unknown type name ‘radio_packet_length_t’
     radio_packet_length_t length;         ///< Length of payload
     ^
In file included from startup.c:24:0:
/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/cpu/native/include/tap.h:40:5: error: unknown type name ‘radio_packet_length_t’
     radio_packet_length_t length;
     ^
make[3]: *** [/home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/bin/startup.o] Fehler 1
make[3]: Verlasse Verzeichnis '/home/martin/Repositories/RIOT-OS/RIOT/cpu/native'
make[2]: *** [native] Fehler 2
make[2]: Verlasse Verzeichnis '/home/martin/Repositories/RIOT-OS/RIOT/cpu'
make[2]: Betrete Verzeichnis '/home/martin/Repositories/RIOT-OS/RIOT/core'
make[2]: Verlasse Verzeichnis '/home/martin/Repositories/RIOT-OS/RIOT/core'
make[2]: Betrete Verzeichnis '/home/martin/Repositories/RIOT-OS/RIOT/drivers'
make[2]: Verlasse Verzeichnis '/home/martin/Repositories/RIOT-OS/RIOT/drivers'
make[2]: Betrete Verzeichnis '/home/martin/Repositories/RIOT-OS/RIOT/sys'
make[3]: Betrete Verzeichnis '/home/martin/Repositories/RIOT-OS/RIOT/sys/memmgnt'
make[3]: Verlasse Verzeichnis '/home/martin/Repositories/RIOT-OS/RIOT/sys/memmgnt'
make[2]: Verlasse Verzeichnis '/home/martin/Repositories/RIOT-OS/RIOT/sys'
make[1]: Verlasse Verzeichnis '/home/martin/Repositories/RIOT-OS/RIOT'
gcc: error: /home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/bin/startup.o: Datei oder Verzeichnis nicht gefunden
gcc: error: /home/martin/Repositories/RIOT-OS/projects/test_memmgnt/../../RIOT/bin/cpu.a: Datei oder Verzeichnis nicht gefunden
make: *** [all] Fehler 1
```

**Comment by mehlis** [comment]
you have to update boards...this is unrelated to this PR

**Comment by miri64** [comment]
okay it works now, sorry for the trouble…

**Comment by miri64** [comment]
ACK

**Comment by mehlis** [comment]
this is moved in the test folder of RIOT. close this

**Pull request closed without merging**
