### PR TITLE
add develhelp option to default makefile

### PR DESCRIPTION
**Pull request by LudwigKnuepfer**

### CODE REVIEW

**Comment by LudwigKnuepfer** [comment]
partially implements https://github.com/RIOT-OS/RIOT/issues/438

**Comment by OlegHahm** [comment]
We should update RIOT's dist/Makefile as well.

**Comment by LudwigKnuepfer** [comment]
I can't do that in a project PR.

**Comment by OlegHahm** [comment]
I know - just to mention it somewhere. ;)

**Comment by LudwigKnuepfer** [comment]
ACK this then? Or will you add this along with your project merge PR?

**Comment by OlegHahm** [comment]
ACK and go.

**Pull request merged**
