### PR TITLE
Release fixes

### PR DESCRIPTION
**Pull request by OlegHahm**
Make projects ready for release and using the RIOT submodule

### CODE REVIEW

**Comment by mehlis** [comment]
ACK

**Comment by miri64** [comment]
ACK

**Comment by OlegHahm** [comment]
I fucked something up - do not merge!

**Comment by LudwigKnuepfer** [comment]
ack (not tested, looks fine)

**Comment by miri64** [comment]
ACK (merge?)

**Comment by OlegHahm** [comment]
Some final changes for the release - please update your acks. ;)

**Comment by miri64** [comment]
ACK

**Pull request merged**
