### PR TITLE
Test hwtimer

### PR DESCRIPTION
**Pull request by LudwigKnuepfer**

### CODE REVIEW

**Comment by OlegHahm** [comment]
What's broken with the test? And why removing it instead of fixing it?

**Comment by LudwigKnuepfer** [comment]
The migration from jam to make broke the test long ago, but the new application breaks the test even more
Also, I thought the upcoming CI might need other tests anyways.

**Comment by OlegHahm** [comment]
Hm, I'd still vote for adopting the test. Removing the jam-Line (pseudoterm resets the msba2 anyway) and adapting to the application change. The CI will still need some time and a rudimentary test is better than no test IMO.

**Comment by LudwigKnuepfer** [comment]
I won't be able to fix the whole string of problems that need to be taken care of to properly fix this test in a reasonable amount of time. Also the test has been dysfunctional for quite a time now which leads me to believe it is not badly needed. I'd rather spend my time on other things now. If you are able to make the test work properly quickly open a new PR please. Otherwise I'll open a ticket if none already exists.

**Comment by LudwigKnuepfer** [comment]
I reincluded the test.

**Comment by OlegHahm** [comment]
```
diff --git test_hwtimer/tests/test_hwtimer test_hwtimer/tests/test_hwtimer
index d391d20..780326e 100755
--- test_hwtimer/tests/test_hwtimer
+++ test_hwtimer/tests/test_hwtimer
@@ -2,8 +2,7 @@

 set timeout 5

-spawn board/msba2/tools/bin/pseudoterm $env(PORT) 
-exec jam reset 
+spawn pseudoterm $env(PORT)

 expect { 
     "OK" {} 
```

fixes the test for MSBA2 (if pseudoterm is in $PATH).

**Comment by OlegHahm** [comment]
In the new version of the test timers are scheduled in a linear fashion. I think it's important to test setting the timers not in order of expiration.

**Comment by LudwigKnuepfer** [comment]
They are scheduled in reverse order.

**Comment by LudwigKnuepfer** [comment]
If you think this makes a difference for the test (is this a regression test?) I can also make the first timer set have the shortest delay.. That way it would be closest to the old behavior.

**Comment by LudwigKnuepfer** [comment]
@OlegHahm I addressed all your comments - anything else you can think of?

**Comment by OlegHahm** [comment]
ACK and go.

**Pull request merged**
