### PR TITLE
add test_vtimer_msg

### PR DESCRIPTION
**Pull request by benpicco**
Add an example for sending vtimer-based messages.

### CODE REVIEW

**Comment by LudwigKnuepfer** [comment]
Has some warnings:

```
main.c:15:8: warning: missing braces around initializer [-Wmissing-braces]
 struct timer_msg msg_a = { .timer = {0}, .interval = { .seconds = 2, .microseconds = 0}, .msg = "Hello World" };
        ^
main.c:15:8: warning: (near initialization for ‘msg_a.timer.queue_entry’) [-Wmissing-braces]
main.c:15:8: warning: missing initializer for field ‘absolute’ of ‘vtimer_t’ [-Wmissing-field-initializers]
In file included from main.c:3:0:
/home/lo/native/projects/test_vtimer_msg/../../RIOT/sys/include/vtimer.h:36:13: note: ‘absolute’ declared here
     timex_t absolute;
             ^
main.c:16:8: warning: missing braces around initializer [-Wmissing-braces]
 struct timer_msg msg_b = { .timer = {0}, .interval = { .seconds = 5, .microseconds = 0}, .msg = "This is a Test" };
        ^
main.c:16:8: warning: (near initialization for ‘msg_b.timer.queue_entry’) [-Wmissing-braces]
main.c:16:8: warning: missing initializer for field ‘absolute’ of ‘vtimer_t’ [-Wmissing-field-initializers]
In file included from main.c:3:0:
/home/lo/native/projects/test_vtimer_msg/../../RIOT/sys/include/vtimer.h:36:13: note: ‘absolute’ declared here
     timex_t absolute;
```

gcc 4.8.2
CFLAGS="-Wall -Wextra -pedantic"

PS:
You don't need to close and open a new PR, just push your changes, possibly squashing with `git rebase -i HEAD~<number of commits to work on>`, has on-line help. If you did that you need to push with -f..

**Comment by mehlis** [comment]
@benpicco don't invest your time in vtimer before talking to @OlegHahm or @kaspar030. It's planned to replace it in the near future...

**Comment by benpicco** [comment]
Am Fri, 25 Oct 2013 07:38:06 -0700
schrieb LudwigOrtmann notifications@github.com:

> Has some warnings:
> 
> ```
> main.c:15:8: warning: missing braces around initializer
> [-Wmissing-braces] struct timer_msg msg_a = { .timer = {0}, .interval
> = { .seconds = 2, .microseconds = 0}, .msg = "Hello World" }; ^
> main.c:15:8: warning: (near initialization for
> ‘msg_a.timer.queue_entry’) [-Wmissing-braces] main.c:15:8: warning:
> missing initializer for field ‘absolute’ of
> ‘vtimer_t’ [-Wmissing-field-initializers] In file included from
> main.c:3:0: /home/lo/native/projects/test_vtimer_msg/../../RIOT/sys/include/vtimer.h:36:13:
> note: ‘absolute’ declared here timex_t absolute; ^
> ```

This should be directly related to
http://gcc.gnu.org/bugzilla/show_bug.cgi?id=53119

Or how should I initialize the struct with 0? memset?

> PS:
> You don't need to close and open a new PR, just push your changes,
> possibly squashing with 'git rebase -i HEAD~<number of commits to
> work on>', has on-line help. If you did that you need to push with
> -f..

I'm already doing this, but does really update the pull request?
#42 still points to the old code.

**Comment by benpicco** [comment]
> @benpicco don't invest your time in vtimer before talking to
> @OlegHahm or @kaspar030. It's planned to replace it in the near
> future...

Hm, what other options are there to, say, call a function every 3s?

**Comment by LudwigKnuepfer** [comment]
I don't know how github handles closed pull requests, but it should say on this very page that you can push to it and that is what I've been doing with my PRs for a while now...

**Comment by mehlis** [comment]
@benpicco my note about the vtimer module was not related to your code. I just want you to talk to @OlegHahm  before investing more time in the vtimer code.

**Comment by benpicco** [comment]
This unfortunately also has an issue when the two timers are close to each other and they are supposed to do some work after waking up: the other timer will interrupt the work and the timer is forever lost.

e.g. setting both timers to 1s and doing some time-intensive calculation will trigger this
https://gist.github.com/benpicco/7191330

I'm still wondering if there is some way around this…

**Comment by LudwigKnuepfer** [comment]
I guess the lost messages are a vtimer bug. This path is taken:

```
    /* shoot timer */
    if (timer->action == (void *) msg_send_int) {
        msg_t msg;
        msg.type = MSG_TIMER;
        msg.content.value = (unsigned int) timer->arg;
        msg_send_int(&msg, timer->pid);
    }
    else ...
```

And this is the declaration of `msg_send_int`:

```
/**
 * @brief Send message from interrupt.
 *
 * Will be automatically chosen instead of msg_send if inISR() == true
 *
 * @param  m pointer to message structure
 * @param  target_pid PID of target thread
 *
 * @return 1 if sending was successfull
 * @return 0 if receiver is not waiting and block == false
 */
int msg_send_int(msg_t *m, unsigned int target_pid);
```

Note, that the return value of  `msg_send_int` is not checked. As vtimer is deprecated this is a won't fix.

**Comment by benpicco** [comment]
> As vtimer is deprecated this is a won't fix.

What should be used instead?

**Comment by LudwigKnuepfer** [comment]
Right now you could just sleep between function calls/loop iterations in a thread.

**Comment by LudwigKnuepfer** [comment]
(Of course, if you are hell bent on using this functionality you can go ahead and start fixing vtimer...)

**Comment by benpicco** [comment]
> I guess the lost messages are a vtimer bug. This path is taken:
> 
> ```
>     /* shoot timer */
>     if (timer->action == (void *) msg_send_int) {
>         msg_t msg;
>         msg.type = MSG_TIMER;
>         msg.content.value = (unsigned int) timer->arg;
>         msg_send_int(&msg, timer->pid);
>     }
>     else ...
> ```
> 
> And this is the declaration of `msg_send_int`:
> 
> ```
> /**
>  * @brief Send message from interrupt.
>  *
>  * Will be automatically chosen instead of msg_send if inISR() == true
>  *
>  * @param  m pointer to message structure
>  * @param  target_pid PID of target thread
>  *
>  * @return 1 if sending was successfull
>  * @return 0 if receiver is not waiting and block == false
>  */
> int msg_send_int(msg_t *m, unsigned int target_pid);
> ```
> 
> Note, that the return value of  `msg_send_int` is not checked.

Actually, this doesn't look like a vtimer bug.
cib_put() always returns -1 and it looks like cib->write_count is never
decremented.
So that would mean any queueing of messages would fail.
Actually [1] shows just this behaviour.
Might even be related to https://github.com/RIOT-OS/RIOT/issues/272

[1] https://gist.github.com/benpicco/7200223

**Comment by benpicco** [comment]
Oh I guess I should call `msg_init_queue`

**Comment by LudwigKnuepfer** [comment]
No matter what, ignoring the return value of that call is a bug.

**Comment by benpicco** [comment]
Yes, but I think a warning that the queue was full/not present and thus a message was lost should suffice, what else could you do at this point but drop it, if there is no memory to store it?

Registering a queue with msg_init_queue() fixes the problem.

**Comment by LudwigKnuepfer** [comment]
OK then, go ahead and PR =)

**Comment by benpicco** [comment]
So

```
warnx("queue_msg: no memory to queue message");
```

?

**Comment by LudwigKnuepfer** [comment]
Is `<err.h>` supported in newlib?

**Comment by OlegHahm** [comment]
In newlib maybe, but definitely not in msp430lib.

**Comment by benpicco** [comment]
btw, a quick grep shows that almost nobody is checking the return value of `msg_send_int` or `msg_send` which may lead to surprising results…

**Comment by OlegHahm** [comment]
Well, as long as we have the vtimer, I don't see why we shouldn't include a test application for it.
ACK

**Comment by mehlis** [comment]
still has warnings:

```
main.c:15:39: warning: missing field 'data' initializer [-Wmissing-field-initializers]
struct timer_msg msg_a = { .timer = {0}, .interval = { .seconds = 2, .microseconds = 0}, .msg = "Hello World" };
                                      ^
main.c:15:38: warning: suggest braces around initialization of subobject [-Wmissing-braces]
struct timer_msg msg_a = { .timer = {0}, .interval = { .seconds = 2, .microseconds = 0}, .msg = "Hello World" };
                                     ^
                                     {}
main.c:15:39: warning: missing field 'absolute' initializer [-Wmissing-field-initializers]
struct timer_msg msg_a = { .timer = {0}, .interval = { .seconds = 2, .microseconds = 0}, .msg = "Hello World" };
                                      ^
main.c:16:39: warning: missing field 'data' initializer [-Wmissing-field-initializers]
struct timer_msg msg_b = { .timer = {0}, .interval = { .seconds = 5, .microseconds = 0}, .msg = "This is a Test" };
                                      ^
main.c:16:38: warning: suggest braces around initialization of subobject [-Wmissing-braces]
struct timer_msg msg_b = { .timer = {0}, .interval = { .seconds = 5, .microseconds = 0}, .msg = "This is a Test" };
                                     ^
                                     {}
main.c:16:39: warning: missing field 'absolute' initializer [-Wmissing-field-initializers]
struct timer_msg msg_b = { .timer = {0}, .interval = { .seconds = 5, .microseconds = 0}, .msg = "This is a Test" };
                                      ^
6 warnings generated.
```

build with `LANG=C CC=clang CFLAGS="-DHAVE_VALGRIND_VALGRIND_H -Os -W -Wextra -pedantic" make -B clean all`

**Comment by mehlis** [comment]
or do we ignore this kind of warning?

**Comment by OlegHahm** [comment]
I would say, let's ignore them here. It's only an example project, that will vanish soon anyway (1.) some projects, but not all project will be merged into the main repo 2.) the vtimer will be obsolete) - so don't put too many work in this.

**Comment by mehlis** [comment]
agreed + ACK + go

**Pull request merged**
